### ISSUE TITLE
Supported board (Yuehengda) Analog gate Drivers+STM32+different Interface?

### ISSUE THREAD

**Issue by sjdaliyan** [RoboDurden/Hoverboard-Firmware-Hack-Gen2.x#70]
This is a board from one of my hoverboards. 2 mainboards inplace of sideboards.
I read this address searching to be sure support of my board.
https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/wiki
My board looks exactly like the ones with analog gate drives but with stm32f103 instead of GD32. and interfaces looks also different. 

Help me.

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/d00e6055-4f89-4de8-b399-0cd652fafaf8)

 
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/5a5ad77e-c091-4fbd-8b8b-e03ace4670d8)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/877eab51-59c9-4797-ad70-c5f14b9374e4)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/03298d8b-e92e-4d9d-9673-c2148b9893c7)

**Comment by RoboDurden** [comment]
Your board is neither 2.1 nor 2.2 so I will become Gen2_2.3 - if you upload high resolution photos of front and backside of master and of slave board please.

One of these autodetect binaries could work for you 

https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/blob/main/BinariesToTest/hoverboard%20autodetect%20GD%2CSTM_32F103%20tx%3DPB6%2C%20rx%3DPB7.bin

https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/blob/main/BinariesToTest/hoverboard%20autodetect%20GD%2CSTM_32F103%20tx%3DPA2%2C%20rx%3DPA3.bin

Watch my YouTube video on how to use autodetect !!

**Comment by sjdaliyan** [comment]
Thanks for quick reply.
2 boards are identical except slave board doesn't have some of the components not assembled. like radio control module and 36v output regulator.
I will watch autodetect video.

here are master board's pictures:

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/dfe47ad0-2a77-44a5-89ad-457bd0681cbe)


![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/d3586cd9-52b3-468d-b85f-f9f9be1cee41)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/69042537-70b1-489f-b909-2370af765594)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/667f3b43-ce33-4a64-b386-f97cadb9834f)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/62d53969-6bbe-4130-b81c-d90145e1d1e2)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/34aaa454-9032-4997-982d-2b71995b4e3f)

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/6358e260-21f7-4a91-8e2d-cc3ace22fe13)

This is 36v regulator on the master board but missing in the slave board

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/d8e14e43-c887-4670-9ff4-bea799156cf9)

One of the mosfets from the back of the board

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/62d53969-6bbe-4130-b81c-d90145e1d1e2)

**Comment by AILIFE4798** [comment]
quality of the picture is too bad
cannot even see this
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/142502122/23cd19da-7a83-4d5e-adab-e70df0c19cb5)
you need to retake them in a brighter place i guess

**Comment by RoboDurden** [comment]
If autodetect works we no longer need sharp pictures :-)

Where could be the pb6 and pb7 pins ?

**Comment by RoboDurden** [comment]
Looks like this PT2272 is used in cheap remote controls:
![Screenshot_20240228-074955_copy_603x606](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/12238841/72fa2649-d695-42f4-b8b2-a9bf3cd45df3)

**Comment by sjdaliyan** [comment]
Thank you all for contributing. I tried my best to take best pictures i can with my cell phone.
But its unclear where the pa5 and pa6 go bcz track is under soldermask i have to use a cutter and scratch the solder mask. but i guess they are going to the remote chip. 

I watched auto detect video i think i have to afully assembly the board right? 

![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/997d4a77-c0a4-4721-a825-bfef62e581ac)

**Comment by RoboDurden** [comment]
Do not scratch on your PCB .
Simply test some pins until you see smileys..
But first check that these pins are not 5V or higher !

What is the master slave cable socket ?

**Comment by sjdaliyan** [comment]
I will using multimeter.

In this picture ,Connector marked in blue in the middle is the Master-slave Interconnect. 
Are there any schematics available from the boards your firmware support?


![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/19210433/dc116033-5319-41e5-98ff-79ce4cc6633f)

**Comment by RoboDurden** [comment]
Flash the pa2 pa3 binary first and test those master slave pins that are below 5V .

Then try pa6 pa7 binary and check the RC chip pins .

Gd32103 of course.

Autodetect so far has only been tested with gd32f130 ...

And of course: 1-2 A current limiting power supply.
No battery !

**Comment by AILIFE4798** [comment]
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/142502122/c5bcc167-804d-44d3-9cc4-c2a6670b653b)

**Comment by RoboDurden** [comment]
Any Arduino tutorial how to use this  PT2272 as a bidirectional Rx tx Uart bridge ???

**Comment by AILIFE4798** [comment]
pt2272 is only decode to 4 output i doubt it is fast enough for serial
and def not bidirectional because the rf module is only rx

**Comment by AILIFE4798** [comment]
you have a better chance of sucess just directly connect the rf module one to tx and other to rx i think it might work no decoder is needed
in fact i dont know why its used in this case as if decoding is needed the stm32 also can do it with external decoder its even using more gpio

**Comment by sjdaliyan** [comment]
> Any Arduino tutorial how to use this PT2272 as a bidirectional Rx tx Uart bridge ???

This is datasheet of the part.i Think its not possible. bcz its made for another purpose. an external uart transceiver must be soldered in place.I know its complicated and i know these boards are very hard to finds so they are rare. so it may not be worth spending this much time

Only one of these boards is working well during the explosion of battery :) I want to use functional one to control my sewing machine like a servo. i dont care about these Chinese boards much just send me a schematic that works well with your firmware that fine for me.

**Comment by RoboDurden** [comment]
You should be able tons older two thin wires to the two and resistors. 
Either to the MCU sides or the receiver chip side.
Both sides might work.

If you only want to use one board anyway than try the master slave header with the pa2 pa3 autodetect binary. You won't need a second uart port for you sewing machine :-)

Beware of +5V or even +15V on this header.

**Comment by sjdaliyan** [comment]
What about schematic? are there any available to download?

**Comment by RoboDurden** [comment]
Not for your board.

**Comment by sjdaliyan** [comment]
> Not for your board.

Any supported single motor driver board will be ok.i told you earlier i dont care about this board. i will desolder the parts and use them on another board with better support.

**Comment by RoboDurden** [comment]
Sorry, I will not support that.
We gave our best to help you but if you won't even give my autodetect a try then good bye :-(

**Comment by sjdaliyan** [comment]
life means collaboration and cooperation. some sort of give and take. you are not the only one with that information. if you forbid things you know from other in fact you forbid yourself their knowledge. sorry if you dont know any common sense. surely thats expecting too much from some one bragging of being a loser. i will dint my solution with or without your help if you think you have any advantage over me because you know something i dont know you are very wrong. and this is surely spirit of a cave man. living in his cell threatens others. sorry if its normal in your country mate.
