### ISSUE TITLE
Can this be firmware hacked?

### ISSUE THREAD

**Issue by NonTaxx** [RoboDurden/Hoverboard-Firmware-Hack-Gen2.x#78]
![1](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/f0e66adc-c509-4f83-afbe-8c94c8ba20bb)
![2](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/b6122664-aa4f-43e9-892c-183e9db555a7)
![3](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/d7e2e13e-35dc-4b2c-b119-77dda216347f)
![4](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/f32f81c3-dc93-4bb2-9c0b-c965e5688bbd)
![5](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/90250f24-c7fc-4d92-af51-7fb5484cfd73)
![6](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/878a0aa2-06a8-47ef-8b16-34548d4490cf)
![7](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/9a11d7ad-91cb-4b51-af72-ab9a4ea3e4e8)

**Comment by I-hate-2FA** [comment]
yes just the usual f130c8 but without gate driver

**Comment by NonTaxx** [comment]
I don't know where to connect the STLink

**Comment by I-hate-2FA** [comment]
either you are one of the bdc or you didnt read the wiki

**Comment by I-hate-2FA** [comment]
gnd and 3v3 is correct

**Comment by NonTaxx** [comment]
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/d7d562d9-426c-4548-8d71-4368e984c016)
When I try to connect it beeps and I get an error message

**Comment by NonTaxx** [comment]
Should I upgrade the firmware?
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/a54895a8-68b9-4004-aaf9-0a40c12b1d31)

**Comment by RoboDurden** [comment]
Sorry, no time (=happiness) to help you with this beginner steps.
Watch youtube and try autoflash.bat: https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/tree/main/BinariesReadyToFlash

**Comment by I-hate-2FA** [comment]
it could be everything really if you ask me ill tell you to use serial flashing because itll 100% work

**Comment by NonTaxx** [comment]
I succesfully connected it but I don't know which .bin should I flash in

**Comment by NonTaxx** [comment]
I'm green on this stuff, I want it to be a remote controlled hoverboard so I could use it to control my lawn mower. I did my research and found on youtube that I need to flash custom firmware therefore I can connect it to my RC receiver.

**Comment by I-hate-2FA** [comment]
autodetect

**Comment by RoboDurden** [comment]
https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/tree/main/BinariesReadyToFlash

**Comment by NonTaxx** [comment]
![image](https://github.com/RoboDurden/Hoverboard-Firmware-Hack-Gen2.x/assets/108197358/e517c28f-f74f-49e6-a937-d26011ede81e)

**Comment by NonTaxx** [comment]
Which one should I flash in? There are a bunch of versions

**Comment by RoboDurden** [comment]
please start using your brain !

**Comment by NonTaxx** [comment]
Well you told it is 2.1.6 but there is no 2.1.6 .bin file in all of the repository

**Comment by I-hate-2FA** [comment]
i told you to use autodetect,there is 4 option left,you know your mcu number so 2 left,i dont know which one to use either because the picture quality is shit no one can trace it

you are the type of person that dont deserve to use the firmware

**Comment by RoboDurden** [comment]
Well everyone is free to use my firmware.
And no one at all deserves my help.
Because we all should be free :-)
