### ISSUE TITLE
GD32F103 on gen 1 main board

### ISSUE THREAD

**Issue by Clarepz** [RoboDurden/Hoverboard-Firmware-Hack-Gen2.x#8]
The board looks very close to the original one in NiklasFauth first hack but it as a GD32 instead of the STM32. Wich board layout do I need to choose ? Thank you
![PXL_20230421_080010639](https://user-images.githubusercontent.com/63111262/233578932-767c75d3-2a02-4d5a-9dbc-3b6ec90fd4bf.jpg)
![original_88e9c280-16fe-4470-b5a3-be20e5d5a0e2_PXL_20230421_074639881](https://user-images.githubusercontent.com/63111262/233579062-3dc113c4-d0e0-41a3-ae28-552645732ae2.jpg)

**Comment by RoboDurden** [comment]
This is a gen 1 board. The gd32f103 is compatible to the stm32f103.
Choose the eferu foc firmware which is way better then the original Niklas Firmware.

**Comment by Clarepz** [comment]
Thankyou I was confused
